CREATE TABLE "demoDB"."demo"."PLANET" (
		"PLANET_ID" BIGINT NOT NULL,
		"PLANET_NAME" NVARCHAR(255) NULL,
		"PLANET_CREATED_DATE" DATETIME NOT NULL,
		"UPDATED_DATETIME" DATETIME NOT NULL,		
		"CLASS_TYPE" NVARCHAR(255) NULL,
		"ADVANCEMENT_LEVEL" NVARCHAR(255) NULL,
		"PRIMARY_SPECIES" NVARCHAR(255) NULL,
		"POPULATION" NVARCHAR(255) NULL,
		"LANGUAGE" NVARCHAR(255) NULL,
		"CLIMATE" NVARCHAR(255) NULL,	
		"NOTES" VARCHAR(255)		
)
GO

CREATE TABLE "demoDB"."demo".REFERENCE_DATA (
		"ID" INT NOT NULL IDENTITY (1,1),
		"REFTYPE"  VARCHAR(255) NOT NULL,
		"CODE" VARCHAR(255) NOT NULL,
		"DESCRIPTION" VARCHAR(255) NOT NULL		
)
GO