INSERT INTO "demoDB".demo.REFERENCE_DATA (REFTYPE, CODE, DESCRIPTION) VALUES( 'species','HER', 'Hermesians');
INSERT INTO "demoDB".demo.REFERENCE_DATA (REFTYPE, CODE, DESCRIPTION) VALUES( 'species','GAL', 'Galileobinites');

INSERT INTO "demoDB".demo.REFERENCE_DATA (REFTYPE, CODE, DESCRIPTION) VALUES( 'language','NAB', 'Nabuian');
INSERT INTO "demoDB".demo.REFERENCE_DATA (REFTYPE, CODE, DESCRIPTION) VALUES( 'language','GAL', 'Galilian');